// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0TizEj0a4WcP53bmSoYMe4VdtGrMfwg0',
    appId: '1:937049177428:web:607e23bd1580ab3c621cc1',
    messagingSenderId: '937049177428',
    projectId: 'sendbad-devlopment',
    authDomain: 'sendbad-devlopment.firebaseapp.com',
    storageBucket: 'sendbad-devlopment.firebasestorage.app',
    measurementId: 'G-SX9E4P6M6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6qkVwV-7uZXu1oWCmx2IcMW57zDvpvZ0',
    appId: '1:937049177428:android:6e7b6922dd4ec5c1621cc1',
    messagingSenderId: '937049177428',
    projectId: 'sendbad-devlopment',
    storageBucket: 'sendbad-devlopment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfCw8X9AeZkp61QmLakb71lGmtdY8LmOI',
    appId: '1:937049177428:ios:0084fcfd05851b26621cc1',
    messagingSenderId: '937049177428',
    projectId: 'sendbad-devlopment',
    storageBucket: 'sendbad-devlopment.firebasestorage.app',
    iosBundleId: 'com.example.sindbadStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfCw8X9AeZkp61QmLakb71lGmtdY8LmOI',
    appId: '1:937049177428:ios:0084fcfd05851b26621cc1',
    messagingSenderId: '937049177428',
    projectId: 'sendbad-devlopment',
    storageBucket: 'sendbad-devlopment.firebasestorage.app',
    iosBundleId: 'com.example.sindbadStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0TizEj0a4WcP53bmSoYMe4VdtGrMfwg0',
    appId: '1:937049177428:web:8563768ef03c8058621cc1',
    messagingSenderId: '937049177428',
    projectId: 'sendbad-devlopment',
    authDomain: 'sendbad-devlopment.firebaseapp.com',
    storageBucket: 'sendbad-devlopment.firebasestorage.app',
    measurementId: 'G-9PXW3M4B7T',
  );

}